### PR TITLE
Replace "base" with "parent"

### PR DESCRIPTION
**Pull request by JRaspass**
As per the documentation, parent is encouraged these days: 
> Unless you are using the fields pragma, consider this module discouraged in favor of the lighter-weight parent.

Since we don't use the fields pragma let's use parent. It'll only be an extra dep for Perl 5.8 users since it's core in 5.10+.

### CODE REVIEW

**Comment by vanHoesel** [comment]
just because `parent` is encouraged to be used, I rather not bump up Perl to 5.10 for a very 'core' module, being used in legacy code bases. Not so long ago, I had to maintain a code base running on 5.8, sorry!

**Comment by JRaspass** [comment]
This isn't a Perl bump, parent is dual-life. This is one more dep (we already depend on plenty of CPAN) for the miniscule of people on 5.8, many of whom almost certainly already have parent installed. This dist will remain 5.8+.

**Review by haarg — APPROVED** [review]
lgtm

**Review by simbabque — APPROVED** [review]
Lgtm. I am pretty sure one of our deps already depends on this, so even on 5.8 it is most likely going to be there already. Thanks James!

**Comment by oalders** [comment]
I'm going to close and re-open to try to trigger the actions, which had gone dormant.

**Review by genio — APPROVED** [review]

**Comment by oalders** [comment]
Thanks, @JRaspass!

**Pull request merged**
