### PR TITLE
Avoid inconsistent setting of content to undef.

### PR DESCRIPTION
**Pull request by tomhukins**
Better tests suite, travis and MANIFEST.SKIP.

This fixes merge conflicts in #27 submitted by @jeteve.

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @jeteve and @tomhukins!

**Comment by oalders** [comment]
Closes #27

**Comment by jeteve** [comment]
Thanks guys!

**Comment by stuartskelton** [comment]
Ditto

**Pull request merged**
