### PR TITLE
Clean up repetitive backcompat code

### PR DESCRIPTION
**Pull request by Grinnz**
Cleaning up the mess I made in #145

### CODE REVIEW

**Comment by vanHoesel** [comment]
Except for the problems with the versioning and the CHANGES file, it looks all good to me.

#145 was not a mess, but this looks much cleaner

**Review by vanHoesel — APPROVED** [review]

**Comment by oalders** [comment]
Thanks @Grinnz! Could you add a Changelog entry to get the CI past the build job?

**Comment by Grinnz** [comment]
Added. I might suggest that release tests probably shouldn't be run for pull requests though.

**Comment by oalders** [comment]
Thanks for the update!

**Pull request merged**
