### PR TITLE
Add default status_message for unknown status codes (GH#105)

### PR DESCRIPTION
**Pull request by robrwo**
This fixes potential problems when new or unsupported status codes
are used by adding a default status code.

This change also adds tests.

### CODE REVIEW

**Comment by robrwo** [comment]
Note from [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html)

> The Reason-Phrase is intended to give a short textual description of the Status-Code. The Status-Code is intended for use by automata and the Reason-Phrase is intended for the human user. The client is not required to examine or display the Reason- Phrase. 

Ideally, 1xx should be "Informational" and 2xx should be "Success", but some of the `status-old.t` tests would fail. SO I've changed them to both be "OK".

**Comment by oalders** [comment]
Would you be able to apply PerlTidy to just your code changes?  There's an rcfile in the root of the repository.

**Comment by genio** [comment]
Perltidy on that section looks like:

```perl
sub status_message ($) {
    $StatusCode{ $_[0] } || is_info( $_[0] ) ? 'OK'
      : is_success( $_[0] )      ? 'OK'
      : is_redirect( $_[0] )     ? 'Redirect'
      : is_client_error( $_[0] ) ? 'Client Error'
      : is_server_error( $_[0] ) ? 'Server Error'
      :                            undef;
}
```

**Comment by robrwo** [comment]
Perltitied.

**Comment by oalders** [comment]
Thanks @robrwo!

**Comment by vanHoesel** [comment]
THIS BREAKS EVERYTHING

any existing code will now return OK

**Comment by vanHoesel** [comment]
as per issue https://github.com/libwww-perl/HTTP-Message/issues/105, I'd strongly advice against this change

**Comment by genio** [comment]
This will be corrected by merging #109

**Pull request merged**
