### PR TITLE
support PATCH HTTP method

### PR DESCRIPTION
**Pull request by mickeyn**
Hi, I would like to get PATCH method supported by HTTP::Request::Common
Hope the simple addition is reasonable, it works for me.

### CODE REVIEW

**Comment by oalders** [comment]
@mickeyn any chance you could add a test?

**Comment by mickeyn** [comment]
added a copy of the PUT checks with PATCH (I don't see a difference from the client standpoint, but good to verify the keyword works)

**Comment by mickeyn** [comment]
the tests are failing because of some missing dep. not related to my change.

**Comment by oalders** [comment]
Thanks!

**Pull request merged**
