### PR TITLE
fix warnings during HTTP::Config->match #62

### PR DESCRIPTION
**Pull request by vitstradal**

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @vitstradal! Could you add the following to `Changes`?

`    - fix warnings during HTTP::Config->match #62 (GH#152) (Viťas Strádal)`

That should fix the build. We need to stop running that check in this phase of the build, but this will allow it to run for now.

**Comment by vitstradal** [comment]
@oalders is it good?

**Review by oalders — APPROVED** [review]
Great! Thanks very much @vitstradal! 👍

**Comment by oalders** [comment]
A new release will be on CPAN in a few minutes.

**Pull request merged**
