### PR TITLE
Allow size limit of ->decoded_content for untrusted sources

### PR DESCRIPTION
**Pull request by Corion**
Limit decoded body size by manually decoding the compressed content

### CODE REVIEW

**Comment by oalders** [comment]
This build is failing on some Perls.

**Comment by Corion** [comment]
The main fix was to up the Zlib prerequisite to version 2.061 (which is not distributed in core for the older Perls). It now passes, but I also had to change the .travis.yml to make it pick up the prerequisites and actually install them...

**Comment by Corion** [comment]
I don't care much about Hacktoberfest, but I'll rebase and amend the PR

**Comment by Corion** [comment]
Ah - it seems I can't conveniently update this PR as it was made from a different branch in my clone originally. The new PR is at https://github.com/libwww-perl/HTTP-Message/pull/181 .

**Pull request closed without merging**
