### PR TITLE
oalders/revert brotli

### LINKED ISSUE #192: IO::Compress::Brotli causes build errors
Somewhere in the build process, HTTP::Message requests that IO::Compress::Brotli be built. This package is apparently no longer maintained, and consistently fails to build on Windows (see RT 125995). While HTTP::Message itself appears to install OK, each time it fails to build IO::Compress::Brotli. Please consider removing the dependency on that package, if possible.

### PR DESCRIPTION
**Pull request by oalders**
- Revert "Support for Brotli encoding"
- Revert "Support for Brotli encoding"
- Delete t/message-decode-brotlibomb.t
- Update Changes

Closes #192

### CODE REVIEW

**Comment by haarg** [comment]
I can see removing the brotli prereq, but it seems like it would be better to leave in support for using the module if it is installed.

**Comment by oalders** [comment]
My issue with leaving support for people who have it installed is that the module has an unpatched security issue, so I'd rather not encourage it. https://rt.cpan.org/Public/Bug/Display.html?id=143548

Thoughts?

**Comment by oalders** [comment]
Thanks @stigtsp. Given that we have no control over `IO::Compress::Brotli` do you think it's ok to continue to support it here?

**Comment by genio** [comment]
I'd vote to just split it out into a separate dist and move on for now.

**Comment by stigtsp** [comment]
> Thanks @stigtsp. Given that we have no control over `IO::Compress::Brotli` do you think it's ok to continue to support it here?

I believe this is safe assuming that [BrotliDecoderDecompressStream](https://metacpan.org/release/MGV/IO-Compress-Brotli-0.004001/source/Brotli.xs#L75) is processing chunks of length [1048576](https://metacpan.org/release/MGV/IO-Compress-Brotli-0.004001/source/Brotli.xs#L11).

It would be great with a 2nd opinion as I'm not experienced with XS, and might have missed some details.

**Comment by timlegge** [comment]
I have released IO::Compress::Brotli 0.012 that has updated the build to work better on Strawberry perl.  It now only seems to fail only with Visual Studio installed - Happy to fix it but I don't have that configuration.

**Comment by oalders** [comment]
I'm going to close this. Probably should open a new PR which bumps the version number of `IO::Compress::Brotli`.

**Pull request closed without merging**
